[local]
path = "/some/local/path"
target_branch = "deploy"
upstream_base = "upstream/master"

[remote.github]
interface_class = "Buildotron::Remote::Github"
api_url = "https://api.github.com"
api_key = "your-api-key"
repo = "cyrusimap/cyrus-imapd"

[remote.fastmail]
interface_class = "Buildotron::Remote::GitLab"
api_url = "https://gitlab.fm/api/v4"
api_key = "ENV:GITLAB_API_KEY"
repo = "fastmail/cyrus-imapd"

[[build_steps]]
name = "upstream"
remote = "github"
label = "include-in-deploy"
tag_format = "cyrus-%d.%s"

[[build_steps]]
name = "capstone"
remote = "fastmail"
label = "include-in-deploy"
tag_format = "cyrus-%d.%s-fastmail"
