[meta]
remote_order = [ "upstream", "fastmail" ]     # meh

[local]
path = "/some/local/path"
target_branch = "deploy"
upstream_base = "upstream/master"

[remote.upstream]
interface_class = "Buildotron::Remote::Github"
api_url = "https://api.github.com"
api_key = "your-api-key"
repo = "cyrusimap/cyrus-imapd"
label = "include-in-deploy"
tag_format = "cyrus-%d.%s"

[remote.fastmail]
interface_class = "Buildotron::Remote::GitLab"
api_url = "https://gitlab.fm/api/v4"
api_key = "ENV:GITLAB_API_KEY"
repo = "fastmail/cyrus-imapd"
label = "include-in-deploy"
tag_format = "cyrus-%d.%s-fastmail"
